apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: proxmox-insecure-transport
  namespace: traefik
spec:
  insecureSkipVerify: true # From proxmox01.yml & ultrafeeder.yml
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: argocd-transport
  namespace: traefik
spec:
  insecureSkipVerify: true # From argocd.yml
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-https
  namespace: traefik
spec:
  redirectScheme:
    scheme: https
    permanent: true # From bjandlisa.yaml
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nibblesnbits-wildcard
  namespace: traefik
spec:
  secretName: nibblesnbits-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  commonName: "*.nibblesnbits.org"
  dnsNames:
    - "nibblesnbits.org"
    - "*.nibblesnbits.org"