apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: proxmox-insecure-transport
  namespace: traefik
spec:
  insecureSkipVerify: true # From proxmox01.yml & ultrafeeder.yml
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: argocd-transport
  namespace: traefik
spec:
  insecureSkipVerify: true # From argocd.yml
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-https
  namespace: traefik
spec:
  redirectScheme:
    scheme: https
    permanent: true # From bjandlisa.yaml
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`traefik.nibblesnbits.org`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      kind: Rule
      services:
        - name: api@internal # This is a special built-in Traefik service
          kind: TraefikService
  tls:
    certResolver: letsencrypt # From your static config