deployment:
  enabled: true
  additionalVolumes:
    - name: bouncer-key
      secret:
        secretName: crowdsec-bouncer-key # Matches the 'destination.name' above
  additionalVolumeMounts:
    - name: bouncer-key
      mountPath: /etc/crowdsec-bouncer
      readOnly: true

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.nibblesnbits.org`)
    entryPoints:
      - websecure
    
api:
  dashboard: true
  insecure: true

logs:
  general:
    level: INFO
  # This enables access logs, outputting them to Traefik's standard output by default. The [Access Logs Documentation](https://doc.traefik.io/traefik/observability/access-logs/) covers formatting, filtering, and output options.
  access:
    enabled: true

experimental:
  plugins:
    crowdsec-bouncer:
      moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      version: "v1.4.5" # Use the latest stable version

ports:
  web:
    forwardedHeaders:
      trustedIPs: &trustedIPs
        - 127.0.0.1/32
        - 10.0.0.0/8
        - 192.168.0.0/16
  websecure:
    forwardedHeaders:
      trustedIPs: *trustedIPs


additionalArguments:
  - "--providers.kubernetesingress.ingressclass=traefik"

#persistence:
#  enabled: true
#  path: /data