deployment:
  enabled: true

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.nibblesnbits.org`)
    entryPoints:
      - websecure
    
api:
  dashboard: true
  insecure: true

logs:
  general:
    level: DEBUG
  # This enables access logs, outputting them to Traefik's standard output by default. The [Access Logs Documentation](https://doc.traefik.io/traefik/observability/access-logs/) covers formatting, filtering, and output options.
  access:
    enabled: true