deployment:
  enabled: true

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.nibblesnbits.org`)
    entryPoints:
      - websecure
    
api:
  dashboard: true
  insecure: true