# /etc/dnsmasq.conf

# Global Settings
interface=eth0
bind-dynamic

# Load Static leases
conf-file=/etc/dnsmasq.d/static-leases.conf

# Dynamic range for all other booting Workers
dhcp-range=192.168.30.50,192.168.30.150,12h
dhcp-option=option:router,192.168.30.1
dhcp-option=option:dns-server,1.1.1.1

# Enable dnsmasq's built-in TFTP server
enable-tftp
tftp-root=/var/lib/tftpboot
dhcp-option=66,192.168.30.2

# 1. Identify if the request is coming from iPXE
dhcp-userclass=set:ipxe,iPXE

# 2. Architecture Detection (for the first stage)
dhcp-match=set:efi64,option:client-arch,7
dhcp-match=set:efi64,option:client-arch,9
dhcp-match=set:bios,option:client-arch,0

# 3. The Chainload Logic
# If it is NOT iPXE, give them the bootloader to get iPXE started
dhcp-boot=tag:!ipxe,tag:bios,undionly.kpxe,,192.168.30.2
dhcp-boot=tag:!ipxe,tag:efi64,ipxe.efi,,192.168.30.2

# If IT IS already iPXE, tell it to fetch its config from Matchbox
# Note the :8081/boot.ipxe endpoint
dhcp-boot=tag:ipxe,http://192.168.30.2:8080/boot.ipxe


# iPXE Booting
#pxe-service=tag:!ipxe,x86PC,"PXE chainload",undionly.kpxe
#pxe-service=tag:!ipxe,X86-64_EFI,"PXE chainload",ipxe.efi
#dhcp-boot=tag:ipxe,http://192.168.30.2:8080/boot.ipxe
