# /etc/dnsmasq.conf

# Global Settings
interface=end0
bind-dynamic

# Load Static leases
conf-file=/etc/dnsmasq.d/static-leases.conf

# Dynamic range
dhcp-range=192.168.30.50,192.168.30.150,12h
dhcp-option=option:router,192.168.30.1
dhcp-option=option:dns-server,1.1.1.1

# Enable dnsmasq's built-in TFTP server
enable-tftp
tftp-root=/var/lib/tftpboot
dhcp-option=66,192.168.30.2

# --- PXE / Matchbox Bootstrapping ---
# This tells the client to load iPXE if it's a standard BIOS/UEFI client
dhcp-match=set:bios,option:client-arch,0
dhcp-boot=tag:bios,undionly.kpxe
dhcp-match=set:efi32,option:client-arch,6
dhcp-boot=tag:efi32,ipxe.efi
dhcp-match=set:efibc,option:client-arch,7
dhcp-boot=tag:efibc,ipxe.efi
dhcp-match=set:efi64,option:client-arch,9
dhcp-boot=tag:efi64,ipxe.efi
dhcp-userclass=set:ipxe,iPXE
# If the client IS running iPXE, point them to the Matchbox API
# Replace 192.168.30.5 with your Matchbox/Docker host IP
dhcp-boot=tag:ipxe,http://192.168.30.2:8080/boot.ipxe
