apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - service-lb.yaml  # This stays in resources because it's a file with its own GVK

patches:
  # Patch 1: The ConfigMap for the External URL
  - target:
      kind: ConfigMap
      name: argocd-cm
    patch: |-
      - op: add
        path: /data/url
        value: https://argocd.nibblesnbits.org
