apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 7.7.0
    helm:
      releaseName: argocd
      values: |
        global:
          instanceSelectorKey: argoproj.io/instance
          
        configs:
          params:
            server.insecure: true

        server:
          service:
            type: LoadBalancer
            targetPort: 8080
            annotations:
              external-dns.alpha.kubernetes.io/hostname: argocd.chockablock.home

        # FORCE PORT NUMBERS HERE:
        repoServer:
          service:
            targetPort: 8081
        
        dex:
          service:
            targetPort: 5556
            
        notifications:
          metrics:
            service:
              targetPort: 9001
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
