apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-self-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://gitea.nibblesnbits.org/mcpha1bj/chockablock.git'
    targetRevision: HEAD
    path: 'deploy/apps/argocd'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
