apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.goauthentik.io
    targetRevision: 2026.2.1
    chart: authentik
    helm:
      values: |
        env:
          - name: AUTHENTIK_POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: authentik-secrets
                key: postgres-password
        authentik:
          # Tell Authentik not to create its own secret
          enabled: true 
          # You can use a placeholder for the secret_key here 
          # because we override it with the env var below
          secret_key: "dummy-value-replaced-by-vault"
          extraEnvVars:
            - name: AUTHENTIK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: authentik-secrets
                  key: secret-key # Make sure this matches the key in Vault
        sever:
          ingress:
            enabled: true
            hosts:
              - authentik.nibblesnbits.org

        # Ensure the sub-charts (Postgres/Redis) also use the secret
        postgresql:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  
  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
    createNamespace: true
---
# 1. THE CONNECTION
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: authentik-vault-conn
  namespace: authentik
spec:
  # Using the internal K8s DNS name for Vault
  address: http://vault-server.vault.svc.cluster.local:8200 

---
# 3. THE AUTH
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: authentik-vault-auth  # <--- This name must match the Ref below
  namespace: authentik
spec:
  method: kubernetes
  mount: kubernetes
  vaultConnectionRef: authentik-vault-conn
  kubernetes:
    role: authentik-role
    serviceAccount: default

---
# 3. THE SECRET
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  type: kv-v2
  mount: secret 
  path: nibblesnbits/authentik
  destination:
    name: authentik-secrets 
    create: true
  vaultAuthRef: authentik-vault-auth # <--- This now points to the correct name