apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.goauthentik.io
    targetRevision: 2026.2.1
    chart: authentik
    helm:
      values: |
        global:
          env:
            - name: AUTHENTIK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: authentik-secrets
                  key: AUTHENTIK_SECRET_KEY 
            - name: AUTHENTIK_POSTGRESQL__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentik-secrets
                  key: AUTHENTIK_POSTGRESQL__PASSWORD

        authentik:
          error_reporting:
            enabled: true

        server:
          ingress:
            enabled: true
            ingressClassName: "traefik"
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
              traefik.ingress.kubernetes.io/router.tls: "true"
            hosts:
              - authentik.nibblesnbits.org
            tls:
              - secretName: authentik-tls-cert
                hosts:
                  - authentik.nibblesnbits.org
          
        postgresql:
          enabled: true
          auth:
            existingSecret: "authentik-secrets"
            secretKeys:
              userPasswordKey: "AUTHENTIK_POSTGRESQL__PASSWORD"
              adminPasswokubectl get pv -o jsonpath='{.items[*].spec.nfs.path}'rdKey: "AUTHENTIK_POSTGRESQL__PASSWORD"
            usePasswordFiles: false
          primary:
            persistence:
              enabled: true
              size: 20Gi
              existingClaim: "authentik-postgres-data"

  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    createNamespace: true
---
# 1. THE CONNECTION
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: authentik-vault-conn
  namespace: authentik
spec:
  # Using the internal K8s DNS name for Vault
  address: http://vault-server.vault.svc.cluster.local:8200 

---
# 3. THE AUTH
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: authentik-vault-auth  # <--- This name must match the Ref below
  namespace: authentik
spec:
  method: kubernetes
  mount: kubernetes
  vaultConnectionRef: authentik-vault-conn
  kubernetes:
    role: authentik-role
    serviceAccount: default

---
# 3. THE SECRET
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  type: kv-v2
  mount: secret 
  path: nibblesnbits/authentik
  destination:
    name: authentik-secrets 
    create: true
  vaultAuthRef: authentik-vault-auth # <--- This now points to the correct name
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: authentik-postgres-pv-static
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "" # Leave empty to bind to a specific PVC
  nfs:
    server: 192.168.30.3
    path: "/srv/k8s_nfs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-authentik-postgresql-0
  namespace: authentik
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: authentik-postgres-pv-static # This locks it to your data
