apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ds389
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://gitea.nibblesnbits.org/mcpha1bj/chockablock.git'
    path: deploy/components/ds389 
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openunison
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true