apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  project: default
  sources:
    - chart: gitea
      repoURL: 'https://dl.gitea.com/charts/' # The Helm repo
      targetRevision: 12.5.0
      helm:
        valueFiles:
          - $values/deploy/components/gitea/values.yaml
    - repoURL: https://github.com/mcphallb/k8s.git
      targetRevision: HEAD
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gitea
  syncPolicy:
    automated:                             # Enables the "GitOps" auto-sync
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: gitea-ssh
  namespace: gitea
spec:
  entryPoints:
    - gitea-ssh
  routes:
    - match: HostSNI(`*`) # SSH doesn't support SNI, so we use a wildcard
      services:
        - name: gitea-ssh # Name of your Gitea SSH service
          port: 22         # Internal port Gitea listens on
---
# 1. THE CONNECTION
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: gitea-vault-conn
  namespace: gitea
spec:
  # Using the internal K8s DNS name for Vault
  address: http://vault-server.vault.svc.cluster.local:8200 

---
# 3. THE AUTH
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: gitea-vault-auth  # <--- This name must match the Ref below
  namespace: gitea
spec:
  method: kubernetes
  mount: kubernetes
  vaultConnectionRef: gitea-vault-conn
  kubernetes:
    role: gitea-role
    serviceAccount: default

---
# 3. THE SECRET
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: gitea-admin
  namespace: gitea
spec:
  type: kv-v2
  mount: secret 
  path: gitea/admin
  destination:  
    name: gitea-admin
    create: true
  vaultAuthRef: gitea-vault-auth # <--- This now points to the correct name
---
  # 3. THE SECRET
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: gitea-db
  namespace: gitea
spec:
  type: kv-v2
  mount: secret 
  path: gitea/database
  destination:
    name: gitea-db-secret
    create: true
  vaultAuthRef: gitea-vault-auth # <--- This now points to the correct namgiteae