# nibblesnbits-app-controller.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nibblesnbits-website
  namespace: argocd # This lives in the argocd namespace
spec:
  project: default
  source:
    repoURL: https://github.com/mcphallb/k8s.git
    targetRevision: HEAD
    path: deploy/components/nibblesnbits-website # Folder where your website YAMLs live
  destination:
    server: https://kubernetes.default.svc
    namespace: nibblesnbits # <--- This forces the namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Tells ArgoCD to create 'nibblesnbits' if it's missing
