apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openunison-login
  namespace: argocd
spec:
  destination:
    namespace: openunison
    server: 'https://kubernetes.default.svc'
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
    - /webhooks/1/clientConfig/caBundle
    - /webhooks/2/clientConfig/caBundle
    - /webhooks/3/clientConfig/caBundle
    - /webhooks/4/clientConfig/caBundle
    kind: ValidatingWebhookConfiguration
  project: default
  sources:
  - chart: openunison-operator
    helm:
      releaseName: openunison
      valueFiles:
      - $values/userauth/values.yaml
    repoURL: https://nexus.tremolo.io/repository/helm
    targetRevision: 3.0.23

  - chart: orchestra
    helm:
      releaseName: orchestra
      valueFiles:
      - $values/userauth/values.yaml
    repoURL: https://nexus.tremolo.io/repository/helm
    targetRevision: 3.1.34

  - chart: orchestra-login-portal
    helm:
      releaseName: orchestra-login-portal
      valueFiles:
      - $values/userauth/values.yaml
    repoURL: https://nexus.tremolo.io/repository/helm
    targetRevision: 2.3.84

  - repoURL: https://github.com/TremoloSecurityDemos/openunison-argocd.git
    path: userauth
  - ref: values
    repoURL: https://github.com/TremoloSecurityDemos/openunison-argocd.git
  syncPolicy:
    syncOptions:
    - RespectIgnoreDifferences=true
---
# 1. THE CONNECTION
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: openunison-vault-conn
  namespace: openunison
spec:
  # Using the internal K8s DNS name for Vault
  address: http://vault-server.vault.svc.cluster.local:8200 

---
# 3. THE AUTH
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: openunison-vault-auth  # <--- This name must match the Ref below
  namespace: openunison
spec:
  method: kubernetes
  mount: kubernetes
  vaultConnectionRef: openunison-vault-conn
  kubernetes:
    role: openunison-role
    serviceAccount: default

---
# 3. THE SECRET
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: openunison-secrets
  namespace: openunison
spec:
  type: kv-v2
  mount: secret 
  path: openunison/orchestra-keys
  destination:
    name: orchestra-secrets-source 
    create: true
  vaultAuthRef: openunison-vault-auth # <--- This now points to the correct name