apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: super-productivity-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitea.nibblesnbits.org/mcpha1bj/chockablock.git
    targetRevision: HEAD
    path: deploy/components/super-productivity
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true