apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://helm.releases.hashicorp.com'
    chart: vault
    targetRevision: 0.28.0 # Lock this to a version for stability
    helm:
      values: |
        server:
          ui:
            enabled: true
          dataStorage:
            enabled: true
            size: 1Gi
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
