apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bjandlisa-wildcard-cert
  namespace: bjandlisa
spec:
  # This creates a separate secret just for this domain
  secretName: bjandlisa-wildcard-tls 
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - "bjandlisa.org"
    - "*.bjandlisa.org"
