apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nibbles-wildcard-cert
  namespace: traefik # Putting it where Traefik can see it easily
spec:
  secretName: nibbles-wildcard-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - "nibblesnbits.org"
    - "*.nibblesnbits.org"
