apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 10Gi # Default size
  accessModes:
    - ReadWriteMany
  nfs:
    server: SERVER_IP_PLACEHOLDER # We will replace this later
    path: /EXPORT_PATH_PLACEHOLDER
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
