apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.7.1
    helm:
      values: |
        defaultSettings:
          # Match the path created in your Talos extraMounts
          defaultDataPath: /var/lib/longhorn
          # Disable check for host package managers (apt/yum)
          packageManager: false
        csi:
          # Talos kubelet directory
          kubeletRootDir: /var/lib/kubelet
          # Allows volume formatting within the container
          mkfsPropagateHostMount: true
        # Helps avoid issues with ArgoCD sync hooks on immutable nodes
        preUpgradeChecker:
          jobEnabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
