apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.7.1
    helm:
      values: |
        preUpgradeChecker:
          jobEnabled: false
        defaultSettings:
          executable-path: /usr/local/lib/talos/extensions/iscsi-tools/bin/iscsiadm
          defaultDataPath: /var/lib/longhorn
          packageManager: false
          defaultDataLocality: "best-effort"
          defaultReplicaCount: 2
          backupTarget: "s3://s3.us-east-005.backblazeb2.com/Longhorn-Chockablock"
        csi:
          kubeletRootDir: /var/lib/kubelet
          mkfsPropagateHostMount: true
        service:
          ui:
            type: LoadBalancer
            # Optional: If you want a specific IP from your MetalLB pool
            # loadBalancerIP: 192.168.30.50 
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
