apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    # This allows Longhorn to bypass the security errors you are seeing
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
    argocd.argoproj.io/instance: root-bootstrap
