# pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: super-productivity-data
  labels:
    recurring-job.longhorn.io/source: "enabled"
    recurring-job.longhorn.io/s3-nightly: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn # Explicitly use Longhorn
  resources:
    requests:
      storage: 2Gi