# pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: super-productivity-data
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: "nfs-client"
  resources:
    requests:
      storage: 5Gi