apiVersion: v1
kind: Namespace
metadata:
  name: bjandlisa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bjandlisa-website
  annotations:
    external-dns.alpha.kubernetes.io/hostname: bjandlisa.chockablock.home
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bjandlisa-website
  template:
    metadata:
      labels:
        app: bjandlisa-website
    spec:
      imagePullSecrets:
        - name: dockerhub-creds
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: bjandlisa-website
          image: mcpha1bj/bjandlisa:latest
          ports:
            - containerPort: 80 # Change this to 8080 for non-root
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsUser: 1000
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
            - name: run-volume
              mountPath: /run
            - name: var-cache-volume
              mountPath: /var/cache/nginx
      volumes:
        - name: tmp-volume
          emptyDir: {}
        - name: run-volume
          emptyDir: {}
        - name: var-cache-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: bjandlisa-website
  annotations:
    external-dns.alpha.kubernetes.io/hostname: bjandlisa.chockablock.home
spec:
  type: ClusterIP
  selector:
    app: bjandlisa-website
  ports:
    - protocol: TCP
      port: 80         # Port for the outside world
      targetPort: 80   # Must match the containerPort above
