apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bjandlisa-ingress
  namespace: bjandlisa # Replace with the actual namespace used by that app
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: bjandlisa.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bjandlisa-website # Replace with the actual name of your service
            port:
              number: 80 # Replace with your service's port