apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: default
  namespace: bjandlisa
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: bjandlisa-role
    serviceAccount: default
