apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: dockerhub-pull-secret
  namespace: bjandlisa
spec:
  mount: secret
  type: kv-v2
  path: dockerhub
  vaultAuthRef: default
  destination:
    name: dockerhub-creds # Matches bjandlisa.yaml
    create: true
    type: kubernetes.io/dockerconfigjson
