apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: dockerhub-pull-secret
  namespace: bjandlisa
spec:
  vaultAuthRef: default
  mount: secret        # Changed to match your 'secret/' engine
  type: kv-v2          # Matches your KV version 2 engine
  path: dockerhub      # Matches your secret path
  destination:
    name: dockerhub-creds
    create: true      
    type: kubernetes.io/dockerconfigjson
  refreshAfter: 1h
