apiVersion: batch/v1
kind: Job
metadata:
  name: vault-auto-config
  namespace: vault
spec:
  template:
    spec:
      containers:
      - name: config
        image: hashicorp/vault:1.15
        env:
        - name: VAULT_ADDR
          value: http://vault-internal.vault.svc.cluster.local:8200
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-root-token # The secret you create in the terminal below
              key: token
        command: ["/bin/sh", "-c"]
        args:
          - |
            vault auth enable kubernetes || true;
            vault write auth/kubernetes/config \
                issuer="https://kubernetes.default.svc.cluster.local" \
                kubernetes_host="https://kubernetes.default.svc.cluster.local:443";
            echo 'path "secret/data/dockerhub" { capabilities = ["read"] }' | vault policy write bjandlisa-policy -;
            vault write auth/kubernetes/role/bjandlisa-role \
                bound_service_account_names=default \
                bound_service_account_namespaces=bjandlisa \
                policies=bjandlisa-policy \
                ttl=24h;
      restartPolicy: OnFailure
