apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  vaultAuthRef: static-auth # Must match your VaultAuth resource name
  mount: secret
  path: traefik/cloudflare
  type: kv-v2
  refreshAfter: 1h
  destination:
    name: cloudflare-api-token-secret # This is the K8s secret cert-manager sees
    create: true