apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: paperless-ngx
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres # This MUST match the template label below
  template:
    metadata:
      labels:
        app: postgres # The "badge" for the DB Pod
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_DB
              value: paperless
            - name: POSTGRES_USER
              value: paperless
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: paperless-secrets # The name of the K8s secret created by the Operator
                  key: DB_PASS # The key name inside your Vault secre
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
              subPath: postgres
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "nfs-client"
        resources:
          requests:
            storage: 10Gi
