apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-media
  namespace: paperless-ngx
  labels:
    recurring-job.longhorn.io/source: "enabled"
    recurring-job.longhorn.io/s3-nightly: "enabled"
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: "longhorn"
  resources:
    requests:
      storage: 15Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data
  labels:
    recurring-job.longhorn.io/source: "enabled"
    recurring-job.longhorn.io/s3-nightly: "enabled"
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: "longhorn"
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-consume
  labels:
    recurring-job.longhorn.io/source: "enabled"
    recurring-job.longhorn.io/s3-nightly: "enabled"
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: "longhorn"
  resources:
    requests:
      storage: 1Gi
