# Internal service for the Web UI
apiVersion: v1
kind: Service
metadata:
  name: paperless-web
  namespace: paperless-ngx
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: paperless
  ports:
    - port: 8000
---
# External service for the Printer
apiVersion: v1
kind: Service
metadata:
  name: paperless-ftp
  namespace: paperless-ngx
spec:
  type: LoadBalancer
  selector:
    app: paperless
  ports:
    - name: ftp
      port: 21
      targetPort: 21
    - name: passive
      port: 30000
      targetPort: 30000
    - name: passive-1
      port: 30001
      targetPort: 30001
    - name: passive-2
      port: 30002
      targetPort: 30002
    - name: passive-3
      port: 30003
      targetPort: 30003
    - name: passive-4
      port: 30004
      targetPort: 30004
    - name: passive-5
      port: 30005
      targetPort: 30005
    - name: passive-6
      port: 30006
      targetPort: 30006
    - name: passive-7
      port: 30007
      targetPort: 30007
    - name: passive-8
      port: 30008
      targetPort: 30008
    - name: passive-9
      port: 30009
      targetPort: 30009
