apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: paperless-secrets
  namespace: paperless-ngx
spec:
  vaultAuthRef: paperless-auth
  mount: secret # Your KV mount path
  path: paperless # Your secret path in Vault
  type: kv-v2
  destination:
    name: paperless-secrets # The K8s secret name that Paperless will use
    create: true
  secretMappings:
    - sourceKey: "db_password"
      targetKey: "DB_PASS"
