apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: paperless-auth
  namespace: paperless-ngx
spec:
  vaultConnectionRef: default # <--- Add this line explicitly
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: paperless-role
    serviceAccount: default