apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: paperless-secrets
  namespace: paperless
spec:
  type: kv-v2
  mount: secret # Your Vault KV mount path
  path: paperless # The path to your secret
  destination:
    name: paperless-secrets # The name of the K8s secret to be created
    create: true
  refreshAfter: 1h
