apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: paperless-secrets
  namespace: paperless-ngx
spec:
  type: kv-v2
  mount: secret # Your KV mount path in Vault
  path: paperless/config # Your secret path
  destination:
    name: paperless-secrets # The name of the K8s secret it will create
    create: true
  vaultAuthRef: paperless-vault-auth # <--- THIS points it to the new name