apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless-secrets
  namespace: paperless
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend # The name of your ClusterSecretStore or SecretStore
    kind: ClusterSecretStore
  target:
    name: paperless-secrets # This is the name of the K8s secret ESO will create
    creationPolicy: Owner
  data:
    - secretKey: PAPERLESS_SECRET_KEY
      remoteRef:
        key: secret/data/paperless
        property: secret_key
    - secretKey: DB_PASS
      remoteRef:
        key: secret/data/paperless
        property: db_password
