apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: default
  namespace: paperless-ngx
spec:
  address: http://vault.vault.svc.cluster.local:8200 # Update to your Vault address
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: paperless-ngx
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: paperless-role # This role must exist in Vault
    serviceAccount: default
