apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ds-pvc-data
  namespace: openunison
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "nfs-client"
  resources:
    requests:
      storage: 5Gi  # 389-ds is efficient, 5GB is plenty for a lab
