apiVersion: v1
kind: PersistentVolume
metadata:
  name: meshmonitor-nfs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.30.155 # Update to your NFS Server IP
    path: /mnt/storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meshmonitor-nfs-pvc
  namespace: meshmonitor # Must match the app namespace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
