# values.yaml
network:
  ingress_type: traefik
  host: openunison.nibblesnbits.org
  openunison_host: openunison.nibblesnbits.org
  dashboard_host: dashboard.nibblesnbits.org
  api_server_host: k8s-api.nibblesnbits.org
  ingress_annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"

cert_manager:
  enabled: true # Set to true if using cert-manager, else provide secrets

# Since no external IAM exists, we use a internal setup
orchestra:
  is_internal_db: true 
  enable_provisioning: true
  internal_db:
    prompts:
      - name: uid
        label: User ID
        type: text

# Configures the portal for your users
webapp:
  ingress_enabled: true