apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: openunison-vault-sync
  namespace: openunison
spec:
  # Remove vaultConnectionRef; it will default to the one named "default"
  vaultAuthRef: static-auth 
  mount: secret
  type: kv-v2
  path: openunison/orchestra-keys
  destination:
    name: orchestra-secrets-source
    create: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: default
  namespace: openunison
spec:
  address: http://vault.vault.svc.cluster.local:8200
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: openunison-auth
  namespace: openunison
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    # This must match the 'openunison-role' we created in Vault earlier
    role: openunison-role 
    serviceAccount: default