apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: openunison-vault-sync
  namespace: openunison
spec:
  mount: secret
  type: kv-v2
  path: openunison/orchestra-keys
  destination:
    name: orchestra-secrets-source # This is the name OpenUnison looks for
    create: true
  refreshAfter: 1h