apiVersion: v1
kind: Service
metadata:
  name: openldap-svc
  namespace: openunison
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.30.210 
spec:
  type: LoadBalancer # MetalLB will give this a local IP
  ports:
    - port: 389
      name: ldap
    - port: 636
      name: ldaps
  selector:
    app: openldap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: openunison
spec:
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      labels:
        app: openldap
    spec:
      containers:
        - name: openldap
          image: osixia/openldap:1.5.0
          env:
            - name: LDAP_ORGANISATION
              value: "NibblesnBits"
            - name: LDAP_DOMAIN
              value: "nibblesnbits.org"
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orchestra-secrets-source
                  key: LDAP_ADMIN_PASSWORD
            - name: LDAP_CONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orchestra-secrets-source
                  key: LDAP_CONFIG_PASSWORD
          ports:
            - containerPort: 389
            - containerPort: 636
          volumeMounts:
            - name: ldap-data
              mountPath: /var/lib/ldap
            - name: ldap-config
              mountPath: /etc/ldap/slapd.d
      volumes:
        - name: ldap-data
          persistentVolumeClaim:
            claimName: ldap-pvc-data
        - name: ldap-config
          persistentVolumeClaim:
            claimName: ldap-pvc-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ldap-pvc-data
  namespace: openunison
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: "nfs-client" # Your NFS storage class
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ldap-pvc-config # <--- THIS IS THE ONE THE SCHEDULER CAN'T FIND
  namespace: openunison
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: "nfs-client"
  resources:
    requests:
      storage: 1Gi