services:
  matchbox:
    image: quay.io/poseidon/matchbox:v0.11.0
    container_name: matchbox
    volumes:
      - ./matchbox:/var/lib/matchbox:ro
    ports:
      - "8080:8080"
    command: ["-address=0.0.0.0:8080", "-log-level=debug"]

  dnsmasq:
    image: dockurr/dnsmasq
    container_name: dnsmasq
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf:ro
      - ./dnsmasq/static-leases.conf:/etc/dnsmasq.d/static-leases.conf:ro
      - ./tftpboot:/var/lib/tftpboot:ro
