services:
  # Matchbox Service
  matchbox:
    image: quay.io/poseidon/matchbox:v0.11.0
    container_name: matchbox
    user: "1000:1000"
    ports:
      - "8081:8081" # HTTP for image/config delivery
    volumes:
      - ./matchbox-data:/var/lib/matchbox:Z
    command: ["-address=0.0.0.0:8081", "-log-level=debug"]
    restart: always

  # DHCP/PXE Service
  dnsmasq:
    image: jpillora/dnsmasq
    container_name: dnsmasq
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    command: ["-d", "-q", "-p0", "--enable-tftp", "--tftp-root=/var/lib/tftpboot", "--tftp-no-blocksize"]
    volumes:
      - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
      - ./dnsmasq/nodes.conf:/etc/dnsmasq.d/nodes.conf
      - ./matchbox-data/assets:/var/lib/tftpboot
    restart: always
