clusterName: metal-cluster
talosVersion: v1.12.2
kubernetesVersion: 1.32.0
endpoint: https://192.168.30.10:6443
talsecret: talsecret.yaml

nodes:
  - hostname: control-01
    ipAddress: 192.168.30.10
    controlPlane: true
    installDisk: /dev/sda
    inlinePatch:
      machine:
        install:
          disk: /dev/sda
          image: ghcr.io/siderolabs/installer:v1.12.2
          bootloader: true
  - hostname: wk-01
    ipAddress: 192.168.30.20
    controlPlane: false
    installDisk: /dev/sda
  - hostname: wk-02
    ipAddress: 192.168.30.21
    controlPlane: false
    installDisk: gdev/sda  
